source "https://github.com/CocoaPods/Specs"
source "git@git.qcloud.com:qcloud_u/cocopoads-repo.git"


target 'TACSamples' do
  use_frameworks!
  pod "QCloudCore"
  pod 'TACCore'
  pod 'TACCrash'
  pod 'TACStorage'
  pod 'TACMessaging'
  pod 'TACAuthorization'
  pod 'TACSocialQQ'
  pod 'TACAuthorizationQQ'
  pod 'TACAuthorizationWechat'
  pod 'TACSocialWechat'
  pod 'AOPKit'
  pod 'TACPayment'
  target 'TACSamplesTests' do
    inherit! :search_paths
  end
  target 'TACSamplesUITests' do
    inherit! :search_paths
  end
end
