require "rake"
desc "update local cocoapods"
task :update  do
  Rake::sh "pod update --no-repo-update"
end

task :prepare_dev do
  sh "cp Podfile.dev Podfile"
end

task :prepare_release do
  sh "cp Podfile.release Podfile"
end
desc "default"
task :default => [ :prepare_dev, :update] do

end


desc "test_release"
task :test_release => [ :prepare_release, :update] do

end
